#!/usr/bin/env python3
"""Regenerate deploy/security/trivy-triage.md from a trivy scan.

    python deploy/security/generate_triage.py                 # scans lotspot-preview:latest
    python deploy/security/generate_triage.py --json scan.json  # reuse a scan

deploy/tests/test_image_vulnerabilities.py fails if any finding trivy reports
is absent from the generated document, so this must be re-run whenever the
image or the vulnerability DB moves.
"""

import argparse
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

DOC = Path(__file__).resolve().parent / "trivy-triage.md"
SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]

RUNTIME_PACKAGES = {
    "fastapi", "uvicorn", "starlette", "pydantic", "pydantic-core", "anyio",
    "httptools", "websockets", "watchfiles", "uvloop", "click", "h11",
}

DISPOSITIONS = {
    "fix-available": (
        "**FIX AVAILABLE — must patch.** Upstream has published a fixed "
        "version; shipping this is a choice, not a constraint."
    ),
    "runtime-dep": (
        "**APP DEPENDENCY — must patch.** Lives in the application's own "
        "import graph, so it is directly exploitable through app code paths."
    ),
    "base-no-fix": (
        "**ACCEPTED — no upstream fix.** Debian trixie has not published a "
        "fixed version. The package is inherited from python:3.12-slim and is "
        "not invoked by the application at runtime. Re-scan periodically; this "
        "moves to *must patch* the moment a FixedVersion appears."
    ),
}


def classify(vuln):
    if vuln.get("FixedVersion"):
        return "fix-available"
    if vuln.get("PkgName", "").lower() in RUNTIME_PACKAGES:
        return "runtime-dep"
    return "base-no-fix"


def load(args):
    if args.json:
        return json.loads(Path(args.json).read_text())
    proc = subprocess.run(
        ["trivy", "image", "--scanners", "vuln", "--format", "json", args.image],
        capture_output=True, text=True, timeout=900,
    )
    if proc.returncode != 0:
        sys.exit(f"trivy failed:\n{proc.stderr[-2000:]}")
    return json.loads(proc.stdout)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", default="lotspot-preview:latest")
    ap.add_argument("--json", help="reuse an existing trivy JSON report")
    args = ap.parse_args()

    report = load(args)
    vulns = [
        {**v, "_target": r.get("Target"), "_class": r.get("Class")}
        for r in report.get("Results") or []
        for v in r.get("Vulnerabilities") or []
    ]

    by_sev = defaultdict(list)
    for v in vulns:
        by_sev[v.get("Severity", "UNKNOWN")].append(v)

    image_ref = (report.get("ArtifactName") or args.image)
    trivy_version = (report.get("Trivy") or {}).get("Version", "unknown")

    out = [
        "# Trivy triage — `lotspot-preview`",
        "",
        "Generated by `deploy/security/generate_triage.py`. **Do not hand-edit** —",
        "`deploy/tests/test_image_vulnerabilities.py` fails when a finding trivy",
        "reports is missing here, so regenerate instead.",
        "",
        f"- Image: `{image_ref}`",
        f"- Trivy: `{trivy_version}`",
        f"- Findings: **{len(vulns)}**",
        "",
        "## Disposition key",
        "",
    ]
    for key, text in DISPOSITIONS.items():
        out.append(f"- `{key}` — {text}")
    out += ["", "## Summary", "", "| Severity | Findings | Fix available | Accepted |", "|---|---|---|---|"]

    for sev in SEVERITY_ORDER:
        items = by_sev.get(sev, [])
        if not items:
            continue
        fixable = sum(1 for v in items if classify(v) == "fix-available")
        out.append(f"| {sev} | {len(items)} | {fixable} | {len(items) - fixable} |")

    total_fixable = sum(1 for v in vulns if classify(v) == "fix-available")
    out += [
        f"| **Total** | **{len(vulns)}** | **{total_fixable}** | **{len(vulns) - total_fixable}** |",
        "",
    ]

    for sev in SEVERITY_ORDER:
        items = by_sev.get(sev, [])
        if not items:
            continue
        out += [
            f"## {sev}",
            "",
            f"{len(items)} finding(s).",
            "",
            "| CVE | Package | Installed | Fixed in | Disposition |",
            "|---|---|---|---|---|",
        ]
        for v in sorted(items, key=lambda x: (x.get("PkgName", ""), x["VulnerabilityID"])):
            fixed = v.get("FixedVersion") or "—"
            out.append(
                f"| {v['VulnerabilityID']} | `{v.get('PkgName')}` | "
                f"`{v.get('InstalledVersion')}` | {fixed} | `{classify(v)}` |"
            )
        out.append("")

    DOC.write_text("\n".join(out))
    print(f"wrote {DOC} — {len(vulns)} findings, {total_fixable} with a fix available")


if __name__ == "__main__":
    main()
